title: NIAID BCBB Training Seminars
theme: jekyll-theme-minimal
repository: niaid/training-schedule
url: "https://github.com/niaid/training-schedule"

exclude: [.gitignore, Gemfile, README.md, bashrc]

plugins:
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-relative-links

permalinks: pretty
kramdown:
  entity_output: :as_input
  hard_wrap: true
  auto_ids: true
gfm_quirks: []
